### ISSUE TITLE
Is it possible to refresh or re initialize

### ISSUE THREAD

**Issue by sienedo** [lexkrstn/jquery-sked-tape#15]
i got error when calling again the function
Error: SkedType plugin has been initialized yet

**Comment by emas00** [comment]
I have the same issue. Did you find a workaround?

**Comment by emas00** [comment]
@sienedo I have the same issue. Did you find a workaround?

**Comment by sienedo** [comment]
@emas00 for now i only re initialize by calling the script with ajax.

**Comment by lexkrstn** [comment]
Fixed in v1.4.6.
Also you may destroy an instance with `$sked.skedTape('destroy')`.

**Comment by sienedo** [comment]
well if i destroy it i might initialize it again without ajax right?

**Comment by lexkrstn** [comment]
Yes, that's correct.

**Comment by delzey** [comment]
This error still occurs in 2.4.6 - Can you provide a working example? I have tried many different combinations and result in the same
